poliproyecto/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from accounts.views import login, logout
from userstory.views import ver_archivo
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.home),
    url(r'^login/', login),
    url(r'^logout/', logout),
    url(r'^admin/', admin.site.urls),
    url(r'^index/', views.index),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^proyectos/', include('proyecto.urls')),
    url(r'^usuarios/', include('usuarios.urls')),
    url(r'^roles/', include('rol.urls')),
    url(r'^clientes/',include('clientes.urls')),
    path(route='media/<int:archivo_id>/', view=ver_archivo, name='ver_archivo')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rol/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
"""
URL para el ver, crear y modificar roles
"""

urlpatterns = [
	url(r'^$', views.RolListView.as_view(),name='rol_list'),
	url(r'^create/$', views.CreateRolView.as_view(), name='create_rol'),
	path(route='modificar/<int:pk>/', view=views.UpdateRolView.as_view(), name='update_rol'),
	path(route='ver/<int:pk>/', view=views.VerRolDetailView.as_view(), name='ver_rol')
]

userstory/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *

"""
URL para el tipo de User Story, crear, listar y modificar
"""
urlpatterns = [
    url(r'^$', UserStoryListView.as_view(), name='user_story_list'),
    path('create/', view=CreateUserStoryView.as_view(), name='create_userstory'),
    path('modificar/<int:pk>/', view=UpdateUserStoryView.as_view(), name='update_userstory'),
    path(route='ver/<int:pk>/', view=VerUserStoryDetailView.as_view(), name='ver_userstory')
]

userstory/models.py
import pickle

from django.core.exceptions import ValidationError
from django.db import models
from django.http import HttpResponse

"""
Definicion de los estados de User Story
"""
PENDIENTE = 2
ASIGNADO = 1
FINALIZADO = 0
ESTADOS_US = (
    (PENDIENTE, 'Pendiente'),
    (ASIGNADO, 'Asignado'),
    (FINALIZADO,'Finalizado')
)

"""
Se definen los estados en fase
"""

ESTADOS_EN_FASE = (
    ('To Do', 'To Do'),
    ('Doing', 'Doing'),
    ('Done', 'Done'),
    ('Control de Calidad', 'Control de Calidad'),
)

"""
Metodo que realiza la validacion del rango permitido para los campos de: Valor de Negocio, Prioridad y Valor tecnico 
"""
def rango(valor):
    """
    Validación de rango permitido
    """
    if valor >10 or valor < 0:
        raise ValidationError('El valor debe estar en 0-10')

"""
Se define el modelo User Story
"""
class UserStory(models.Model):
    """
    Modelo de la clase User Story, el cual representa un conjunto de tareas a ser realizadas
    en un periodo de tiempo especificado
    """
    sprints_asignados = models.ManyToManyField('sprint.Sprint', blank=True, related_name='userstory_sprint_asignado')
    estado_fase = models.CharField(max_length=30, choices=ESTADOS_EN_FASE, default='To Do')
    flujo = models.ForeignKey('flujo.Flujo', on_delete=models.PROTECT)
    fase = models.ForeignKey('flujo.Fase', on_delete=models.PROTECT, null=True, blank=True)
    proyecto = models.ForeignKey('proyecto.Proyecto', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(max_length=300)
    fecha_inicio = models.DateField('Fecha de inicio del User Story', null=True, blank=True)
    duracion_estimada = models.PositiveIntegerField(null=True)
    duracion_restante = models.IntegerField(null=True,blank=True)
    valor_negocio = models.PositiveIntegerField(validators=[rango])
    prioridad = models.PositiveIntegerField(validators=[rango])
    valor_tecnico = models.PositiveIntegerField(validators=[rango])
    estado = models.PositiveIntegerField(default=PENDIENTE, choices=ESTADOS_US)
    team_member = models.ForeignKey('usuarios.Usuario', on_delete=models.CASCADE, blank=True, null=True)
    tipo_us = models.ForeignKey('tipoUserStory.TipoUserStory', on_delete=models.PROTECT)
    sprint = models.ForeignKey('sprint.Sprint', on_delete=models.PROTECT, null=True, blank=True)

    def __str__(self):
        """
        Retorna el nombre del User Story actual
        :return: nombre del objeto actual
        """
        return self.nombre

    def set_priorizacion(self):
        return (2*self.valor_negocio + self.prioridad + 2*self.valor_tecnico)/4

    priorizacion = property(set_priorizacion)

    def has_team_member(self):
        """
        retorna falso si el user story no esta asignado a ningun team member, en caso contrario
        retorna verdadero
        :return: True o False
        """
        if not self.team_member:
            return False
        return True

    def has_duracion_estimada(self):
        """
        retorna falso si el user story no tiene una duracion estimada o su duracion
         estimada es 0, en caso contrario retorna verdadero
        :return: True o False
        """
        if not self.duracion_estimada or self.duracion_estimada == 0:
            return False
        return True

    def validate_asignacion(self):
        """
        retorna falso si el user story no tiene un team member asignado o si no se le ha
        asignado una duracion estimada o su duracion estimada es 0
        :return: True o Excepcion
        """
        if not self.has_team_member():
            raise ValidationError('Debe asignar un team member al user story ' + str(self.nombre))
        if not self.has_duracion_estimada():
            raise ValidationError('Se deben estimar las horas de duración del user story ' + str(self.nombre))
        if not self.duracion_restante:
            raise ValidationError('Se deben estimar las horas de duración del user story ' + str(self.nombre))
        if self.duracion_restante <= 0:
            raise ValidationError('Debe indicar una duracion estimada mayor a 0 al user story ' + str(self.nombre))
        return True

    def get_horas_trabajadas(self, sprint=None):
        """
        metodo de la clase de user stories que retorna la cantidad de horas trabajadas
        hasta el momento en el user story
        :return: las horas trabajadas en el user story actual
        """
        if not sprint:
            actividades = Actividad.objects.filter(us=self.pk)
        else:
            actividades = Actividad.objects.filter(us=self.pk, sprint=sprint)
        horas = 0.0
        for actividad in actividades:
            horas += actividad.duracion
        return horas


class Nota(models.Model):
    """
        Clase para adjuntar una nota a un US
    """
    nota = models.TextField()
    us = models.ForeignKey('UserStory', on_delete=models.CASCADE, null=True)
    usuario = models.ForeignKey('usuarios.Usuario', on_delete=models.PROTECT, null=True)
    fecha = models.DateTimeField(auto_now_add=True)
    sprint = models.ForeignKey('sprint.Sprint', on_delete=models.CASCADE)

    def __str__(self):
        """
        Retorna el contenido de la nota actual
        :return: campo nota del objeto actual
        """
        return self.nota


class Archivo(models.Model):
    """
    Clase para adjuntar un archivo a un US
    """
    titulo = models.CharField(max_length=255, blank=True)
    archivo = models.FileField(upload_to='')
    binario = models.BinaryField(null=True, blank=True)
    fecha = models.DateTimeField(auto_now_add=True)
    us = models.ForeignKey('UserStory', on_delete=models.CASCADE, null=True)
    usuario = models.ForeignKey('usuarios.Usuario', on_delete=models.PROTECT, null=True)
    sprint = models.ForeignKey('sprint.Sprint', on_delete=models.CASCADE)

    def __str__(self):
        """
        Retorna el titulo del Archivo actual
        :return: titulo del objeto actual
        """
        return self.titulo

    def set_data(self, data):
        self.binario = pickle.dumps(data)

    def get_data(self):
        return pickle.loads(self.binario)

class Actividad(models.Model):
    """
    Clase para agregar una actividad a un User Story
    """
    nombre = models.CharField(max_length=20)
    descripcion = models.TextField()
    duracion = models.IntegerField()
    usuario = models.ForeignKey('usuarios.Usuario', on_delete=models.PROTECT)
    us = models.ForeignKey('UserStory', on_delete=models.CASCADE, null=True)
    fecha = models.DateTimeField()
    sprint = models.ForeignKey('sprint.Sprint', on_delete=models.CASCADE)
    fase_us = models.ForeignKey('flujo.Fase', on_delete=models.CASCADE,null=True,blank=True)
    estado_fase = models.CharField(max_length=30, choices=ESTADOS_EN_FASE, default='To Do')

    def __str__(self):
        """
        Retorna el nombre del objeto actual
        :return: nombre del objeto actual
        """
        return self.nombre

class CambioEstado(models.Model):
    descripcion = models.TextField()
    usuario = models.ForeignKey('usuarios.Usuario', on_delete=models.PROTECT)
    us = models.ForeignKey('UserStory', on_delete=models.CASCADE, null=True)
    fecha = models.DateTimeField(auto_now_add=True)
    sprint = models.ForeignKey('sprint.Sprint', on_delete=models.CASCADE)
    fase = models.ForeignKey('flujo.Fase', on_delete=models.CASCADE,null=True)
    estado_fase = models.CharField(max_length=30, choices=ESTADOS_EN_FASE, null=True, blank=True)

    def __str__(self):
        """
        Retorna la descripcion del objeto actual
        :return: descripcion del objeto actual
        """
        return self.descripcion

class HistorialEstimaciones(models.Model):
    duracion_estimada = models.PositiveIntegerField()
    sprint = models.ForeignKey('sprint.Sprint', on_delete=models.CASCADE)
    us = models.ForeignKey('UserStory', on_delete=models.CASCADE, null=True)

userstory/forms.py
from django import forms
from .models import *

class CreateUserStoryForm(forms.ModelForm):
    """
    Formulario de la creacion de User Story
    """
    class Meta:
        model = UserStory
        fields = ('proyecto',
                  'nombre',
                  'descripcion',
                  'duracion_estimada',
                  'valor_negocio',
                  'prioridad',
                  'valor_tecnico',
                  'tipo_us',
                  'flujo',
                  )

        widgets = {
            'proyecto': forms.HiddenInput,
        }

class UpdateUserStoryForm(forms.ModelForm):
    """
    Formulario de la modificacion de User Story
    """
    class Meta:
        model = UserStory
        fields = ('proyecto',
                  'nombre',
                  'descripcion',
                  'duracion_estimada',
                  'valor_negocio',
                  'prioridad',
                  'valor_tecnico',
                  'tipo_us',
                  'flujo',
                  )

        widgets ={
            'proyecto': forms.HiddenInput,
        }


class ArchivoForm(forms.ModelForm):
    """
    Formulario para subir archivos al User Story
    """
    class Meta:
        model = Archivo
        """Campos a ingresar"""
        fields = ('titulo', 'archivo', )


class NotaForm(forms.ModelForm):
    """
    Formulario para subir notas al User Story
    """
    class Meta:
        model = Nota
        """Campos a ingresar"""
        fields = ('nota',)


class ActividadForm(forms.ModelForm):
    """
    Formulario para agregar actividades al User Story
    """
    class Meta:
        model = Actividad
        """Campos a ingresar"""
        fields = ('nombre','descripcion','duracion')


class GuardarNotaForm(forms.ModelForm):
    """
    Formulario para guardar notas en el user story
    """
    class Meta:
        model = Nota
        """Campos a ingresar"""
        fields = ('us', 'usuario', 'nota','sprint')


class GuardarArchivoForm(forms.ModelForm):
    """
    Formulario para guardar archivos en el User Story
    """
    class Meta:
        model = Archivo
        """Campos a ingresar"""
        fields = ('titulo', 'archivo','us','usuario','sprint')


class GuardarActividadForm(forms.ModelForm):
    """
    Formulario para guardar actividades en el User Story
    """
    class Meta:
        model = Actividad
        """Campos a ingresar"""
        fields = ('nombre','descripcion','duracion','us','usuario','sprint','fase_us','estado_fase')

templates/userstory/ProductBacklog.html
{% if 'Ver Product Backlog' in permisos %}
{% include 'base.html' %}
<div class="container">
    <div class="head">
        <h1 align="center">{{ title }}</h1>
        <hr>
        <h3 style="text-align: center">Proyecto: {{ project.nombre }}</h3>
    </div>
    <div class="body">
        <a target="_blank" href="{% url 'reporte_pb' project.pk %}">
            <button type="button" class="btn btn-success">
                <i class="fas fa-file-pdf"></i> Exportar a PDF</button>
        </a>
        <table class="table table-sm scrolltable" width="100%">
            <thead class="thead-dark thead">
                <tr>
                    <th width="10%">ID</th>
                    <th width="25%">Nombre</th>
                    <th width="25%">Duracion Estimada</th>
                    <th width="20%">Estado</th>
                    <th width="20%">Priorizacion</th>
                </tr>
            </thead>
            <tbody class="tbody">
                {% for us in object_list|dictsortreversed:"priorizacion"|dictsortreversed:"estado" %}
                    <tr>
                        <td width="10%">{{ us.pk }}</td>
                        <td width="25%">
                            <div class="enlace">
                                <a href="#UserStory_{{ us.pk }}" data-toggle="modal"
                                role="button" class="enlace">
                                {{ us.nombre }}</a>
                            </div>
                        </td>
                        <td width="25%">{{ us.duracion_estimada }}</td>
                        <td width="20%">{{ us.get_estado_display }}</td>
                        <td width="20%">{{ us.priorizacion }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<!-- modales de user stories -->
{% for us in object_list %}
<div id="UserStory_{{ us.pk }}" class="modal fade">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content modal-us">
            <div class="modal-header">
                <h5 class="modal-title w-100 text-center">{{ us.nombre }} </h5>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                <div class="texto">
                    <li>
                        Descripcion: {{ us.descripcion }}
                    </li>
                    <li>
                        Estimacion: {{ us.duracion_estimada }} horas
                    </li>
                    <li>
                        Total de horas trabajadas: {{ us.horas_total }} horas
                    </li>
                    <li>
                        Asignado: {{ us.team_member.username }}
                    </li>
                    <br>
                </div>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="container" id="formulario-nuevo-{{ us.pk }}">
                    </div>
                    <button type="button" id="cancelar-{{ us.pk }}" value="{{ us.pk }}" class="btn btn-danger cancelar-form" style="margin-left: 200px;display: none;">Cancelar</button>
                    <button type="submit" id="guardar-{{ us.pk }}" value="{{ us.pk }}" class="btn btn-success" style="display: none">Guardar</button>
                    <input type='hidden' name='us' value="{{ us.pk }}">
                    <input type='hidden' name='usuario' value="{{ usuario.pk }}">
                </form>
                <hr>
                <h5 class="w-100 text-center">Historial de US:
                <button type="button" id="notas-btn-{{ us.pk }}" value="{{ us.pk }}" class="btn btn-light notas-btn">Notas</button>
                <button type="button" id="archivos-btn-{{ us.pk }}" value="{{ us.pk }}" class="btn btn-dark archivos-btn">Archivos</button>
                <button type="button" id="actividades-btn-{{ us.pk }}" value="{{ us.pk }}" class="btn btn-dark actividades-btn">Actividades</button>
                </h5><hr>
                <div class="container" id="notas-us-{{ us.pk }}">
                    {% for key, notas in notas.items %}
                        {% if key == us.pk %}
                            {% for nota in notas %}
                                {{ nota.nota }}<br>
                                Autor: {{ nota.usuario }}, {{ nota.fecha }}
                                <div class="container" style="width: 600px;">
                                    <hr>
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="container" id="archivos-us-{{ us.pk }}" style="display: none">
                    {% for key, archivos in archivos.items %}
                        {% if key == us.pk %}
                            {% for archivo in archivos %}
                                {{ archivo.titulo }}: <a href="{% url 'ver_archivo' archivo.pk %}">{{ archivo.archivo }}</a><br>
                                Sprint: {{ archivo.sprint }} <br>
                                Autor: {{ archivo.usuario }}, {{ archivo.fecha }}
                                <div class="container" style="width: 600px;">
                                    <hr>
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="container" id="actividades-us-{{ us.pk }}" style="display: none">
                    {% for key, actividades in actividades.items %}
                        {% if key == us.pk %}
                            {% for actividad in actividades %}
                                {% if actividad.tipo == 'actividad' %}
                                    {{ actividad.nombre }}: {{ actividad.descripcion }}<br>
                                    Duracion: {{ actividad.duracion }} horas<br>
                                    Sprint: {{ actividad.sprint }} <br>
                                    Fase: {% if actividad.fase_us %}
                                                {{ actividad.fase_us.nombre }}
                                          {% elif actividad.estado_fase == 'Control de Calidad'%}
                                                Control de Calidad
                                          {% endif %}
                                    <br>
                                    Autor: {{ actividad.usuario }}, {{ actividad.fecha }}
                                    <div class="container" style="width: 600px;">
                                        <hr>
                                    </div>
                                {% elif actividad.tipo == 'cambio' %}
                                    <div style="color:darkblue">{{ actividad.descripcion }} <br>
                                    Sprint: {{ actividad.sprint }} <br>
                                    Autor: {{ actividad.usuario }}, {{ actividad.fecha }}
                                    <div class="container" style="width: 600px;">
                                        <hr>
                                    </div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<script type="text/javascript">
    $(document).ready(function($) {
        $('.notas-btn').click(function() {
            document.getElementById('archivos-btn-'.concat(this.value)).setAttribute('class','btn btn-dark');
            document.getElementById('notas-btn-'.concat(this.value)).setAttribute('class','btn btn-light');
            document.getElementById('actividades-btn-'.concat(this.value)).setAttribute('class','btn btn-dark');
            document.getElementById('notas-us-'.concat(this.value)).style.display = "block";
            document.getElementById('archivos-us-'.concat(this.value)).style.display = "none";
            document.getElementById('actividades-us-'.concat(this.value)).style.display = "none";
        });

        $('.archivos-btn').click(function() {
            document.getElementById('notas-btn-'.concat(this.value)).setAttribute('class','btn btn-dark');
            document.getElementById('actividades-btn-'.concat(this.value)).setAttribute('class','btn btn-dark');
            document.getElementById('archivos-btn-'.concat(this.value)).setAttribute('class','btn btn-light');
            document.getElementById('archivos-us-'.concat(this.value)).style.display = "block";
            document.getElementById('notas-us-'.concat(this.value)).style.display = "none";
            document.getElementById('actividades-us-'.concat(this.value)).style.display = "none";
        });

        $('.actividades-btn').click(function() {
            document.getElementById('archivos-btn-'.concat(this.value)).setAttribute('class','btn btn-dark');
            document.getElementById('notas-btn-'.concat(this.value)).setAttribute('class','btn btn-dark');
            document.getElementById('actividades-btn-'.concat(this.value)).setAttribute('class','btn btn-light');
            document.getElementById('notas-us-'.concat(this.value)).style.display = "none";
            document.getElementById('archivos-us-'.concat(this.value)).style.display = "none";
            document.getElementById('actividades-us-'.concat(this.value)).style.display = "block";
        });
    });
</script>
{% else %}
Permiso Denegado (Ver Product Backlog)
{% endif %}

templates/userstory/list.html
{% if 'Ver User Stories' in permisos %}
{% include 'base.html' %}
<div class="container">
    <div class="head">
        <h1 align="center">User Stories {{ project.nombre }}</h1>
        <hr>
    </div>
    <div class="body">
        <table class="table table-sm scrolltable" width="100%">
            <thead class="thead-dark thead">
                <tr>
                    <th width="10%">ID</th>
                    <th width="45%">Nombre</th>
                    <th width="24%">Duracion Estimada</th>
                    <th width="12%">Priorizacion</th>
                    <th width="8%">Acciones</th>
                    <th width="3%">
                        {% if project.estado == 'Pendiente' or project.estado == 'Activo' %}
                        {% if 'Crear User Stories' in permisos %}
                            <a href="./create/"><i class="fas fa-plus-square"></i> </a>
                        {% endif %}
                        {% endif %}
                    </th>
                </tr>
            </thead>
            <tbody class="tbody">
                {% for us in object_list %}
                    <tr>
                        <td width="10%">{{ us.pk }}</td>
                        <td width="45%">{{ us.nombre }}</td>
                        <td width="24%">{{ us.duracion_estimada }}</td>
                        <td width="10%">{{ us.priorizacion }}</td>
                        <td id="acciones" width="8%">
                            <a href="{% url 'ver_userstory' project.pk us.pk %}"><i class="fas fa-eye"></i></a>
                            {% if project.estado == 'Pendiente' or project.estado == 'Activo' %}
                            {% if 'Modificar User Stories' in permisos %}
                                <a href="{% url 'update_userstory' project.pk us.pk %}"><i class="fas fa-edit"></i></a>
                            {% endif %}
                            {% endif %}
                        </td>
                        <td width="3%"></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% else %}
Permiso Deneagado
{% endif %}

templates/userstory/userstory.html
{% if 'Crear User Stories' in permisos and not object.nombre or 'Modificar User Stories' in permisos and object.nombre %}
{%include 'base.html'%}
<html>
<body>
<div class="container">
    <div class="head">
        <h1 align="center"> {{ title }} </h1>
        <hr>
        <h3 style="text-align: center">Proyecto: {{ project.nombre }}</h3>
    </div>
    <div class="register">
        <div class="container form-container">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p}}
                <button type="submit" class="btn submit-btn">Guardar</button>
            </form>
        </div>
        <hr>
    </div>
</div>

{% for tipo_us in tipos_us %}
    <select name="flujo" required id="flujos_{{ tipo_us.pk }}" style="display: none">
        <option value="" selected>-----------------------------</option>
        {% for key, flujos in flujos.items %}
            {% if key == tipo_us.pk %}
                {% for flujo in flujos %}
                    <option value="{{ flujo.pk }}">{{ flujo.nombre }}</option>
                {% endfor %}
            {% endif %}
        {% endfor %}
    </select>
{% endfor %}

<select name="tipo_us" required id="tipos_us" style="display: none">
    <option value="">-----------------------------</option>
    {% for tipo_us in tipos_us %}
        <option value="{{ tipo_us.pk }}">{{ tipo_us.nombre }}</option>
    {% endfor %}
</select>

</body>
</html>
<script type="text/javascript">
    $(document).ready(function($) {
        var tipo_selected = document.getElementById('id_tipo_us').value;
        document.getElementById('id_tipo_us').innerHTML = $('#tipos_us').html();
        $('#id_tipo_us').val(tipo_selected);

        if (tipo_selected){
            var flujo_selected = document.getElementById('id_flujo').value;
            var flujos_inicial = $('#flujos_'.concat(tipo_selected)).html();
            document.getElementById('id_flujo').innerHTML = flujos_inicial;
            $('#id_flujo').val(flujo_selected);
        }else {
            document.getElementById('id_flujo').innerHTML = '<option value="">-----------------------------</option>';
        }


        $('#id_tipo_us').change(function() {
            if (this.value){
                var flujos = $('#flujos_'.concat(this.value)).html();
                document.getElementById('id_flujo').innerHTML = flujos;
            }else{
                document.getElementById('id_flujo').innerHTML = '<option value="">-----------------------------</option>';
            }
        });
    });
</script>
{% else %}
    {% if object.nombre %}
        Permiso denegado (Modificar User Stories)
    {% else %}
        Permiso denegado (Crear User Stories)
    {% endif %}
{% endif %}

templates/userstory/ver_userstory.html
{% if 'Ver User Stories' in permisos %}
{%include 'base.html'%}
<html>
<body>
<div class="container">
    <div class="head">
        <h1 align="center"> {{ title }} </h1>
        <hr>
        <h3 style="text-align: center">Proyecto: {{ project.nombre }}</h3>
    </div>
    <div class="register">
        <div class="container detalle" style="font-size: 25px">
            <li>Nombre: {% if object.nombre %} {{ object.nombre }} {% endif %}</li>
            <li>Descripción: {% if object.descripcion %} {{ object.descripcion }} {% endif %}</li>
            <li>Fecha de Inicio: {% if object.fecha_inicio %}{{ object.fecha_inicio }} {% endif %}</li>
            <li>Duración estimada: {% if object.duracion_estimada %}{{ object.duracion_estimada }}{% endif %}</li>
            <li>Valor de negocio: {% if object.valor_negocio %}{{ object.valor_negocio }}{% endif %}</li>
            <li>Prioridad: {% if object.prioridad %}{{ object.prioridad }}{% endif %}</li>
            <li>Valor Técnico: {% if object.valor_tecnico %}{{ object.valor_tecnico }}{% endif %}</li>
            <li>Estado: {% if object.estado %}{{ object.estado }} {% endif %}</li>
            <li>Team Member Asignado: {% if object.team_member %}{{ object.team_member }}{% endif %}</li>
            <li>Tipo de User Story: {% if object.tipo_us.nombre %}{{ object.tipo_us.nombre }}{% endif %}</li>
            <li>Sprint: {% if object.sprint.nombre  %}{{ object.sprint.nombre }}{% endif %}</li>
            <li>Flujo: {% if object.flujo.nombre %}{{ object.flujo.nombre }}{% endif %}</li>
            <li>Fase: {% if object.fase.nombre %}{{ object.fase.nombre }}{% endif %}</li>
            <li>Estado de la Fase: {% if object.fase %}{{ object.estado_fase }}{% endif %}</li>
        </div>
        <br>
        <a href="../../"><button type="button" class="btn submit-btn">
            <i class="fas fa-arrow-left"></i> Atras</button></a>
        <hr>
    </div>
</div>
</body>
</html>
{% else %}
Permiso denegado (Ver User Stories)
{% endif %}